% draw all the components in the GUI interface
function draw_components()
    global fig grid_size game_mode
    set(fig, 'HandleVisibility', 'off');
    % images of computer, player and chess 
    computer_img = uiimage(fig, ...
                           'position', [20, 175, 75, 75],...
                           'ImageSource', './computer.png');
    white_chess = uiimage(fig, ...
                           'position', [35, 135, 50, 50],...
                           'ImageSource', './white.png');
                       
    person_img = uiimage(fig, ...
                           'position', [465, 175, 75, 75],...
                           'ImageSource', './person.png');
                       
    black_chess = uiimage(fig, ...
                           'position', [480, 135, 50, 50],...
                           'ImageSource', './black.png');
                       
    % dropdown menu to change the mode of the game
    mode_label = uilabel(fig, ...
                         'Position', [50, 5, 60, 20], ...
                         'Text', 'Mode:');
                     
    game_mode_dropdown = uidropdown(fig, ...
                    'Items', ["Easy", "Medium", "Hard"], ...
                    'ItemsData', [1, 2, 3], ...
                    'Value', game_mode, ...
                    'Position', [90, 5, 80, 20], ...
                    'ValueChangedFcn', @(game_mode_dropdown, event) change_game_mode(game_mode_dropdown));
                
    % dropdown menu to change the size of the chessboard
    size_label = uilabel(fig, ...
                         'Position', [220, 5, 60, 20], ...
                         'Text', 'Size:');
                       
    chessboard_size_dropdown = uidropdown(fig, ...
                    'Items',["16 X 16", "18 X 18", "20 X 20", "22 X 22", "24 X 24"],...
                    'ItemsData', [16, 18, 20, 22, 24], ...
                    'Value', grid_size,...
                    'Position', [260, 5, 80, 20], ...
                    'ValueChangedFcn', @(chessboard_size_dropdown, event) change_chessboard_size(chessboard_size_dropdown));
                  
    % button to restart the game 
    restart_btn = uibutton(fig, 'push', ...
                   'Text', 'Restart', ...
                   'Position',[400, 5, 100, 20], ...
                   'ButtonPushedFcn', @(restart_btn,event) restart_game());
               
end