function set_stopwatch(input)
global fig stop_flag time timer_display timer_start_btn timer_reset_btn time_str game_timer;

stop_flag = 1;
time = 0;

timer_start_btn = uibutton(fig, 'push', ...
                   'Text', 'START', ...
                   'Position',[200, 365, 80, 20], ...
                   'ButtonPushedFcn', @(timer_start_btn,event) start_timer());
                
timer_reset_btn = uibutton(fig, 'push', ...
                   'Text', 'RESET', ...
                   'Position',[300, 365, 80, 20], ...
                   'ButtonPushedFcn', @(timer_reset_btn,event) reset_timer(input));

if (isscalar(input)) % check for the input
    time = input;
end

display_str = format_time(time);
time_str = display_str;

% countdown timer display
timer_display = uilabel(fig, ...
                    'Text', time_str, ...
                    'Position', [120, 390, 330, 30], ...
                    'BackgroundColor', [0.9 0.9 0.9], ...
                    'FontSize', 20, ...
                    'FontColor', 'r', ...
                    'FontName', 'Menlo', ...
                    'FontWeight', 'bold', ...
                    'HorizontalAlignment', 'center');

% start the timer
game_timer = timer('TimerFcn', @timer_fcn, ... 
                   'Period', 1, ...
                   'TasksToExecute', Inf, ...
                   'ExecutionMode', 'fixedRate');

end


